# キャンセルの伝播 {#キャンセルの伝播 .View_chapterTitle__tslMs}

# [](#%E3%81%93%E3%81%AE%E7%AB%A0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6){.header-anchor-link} この章について {#%E3%81%93%E3%81%AE%E7%AB%A0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6}

ここからは、

-   同じcontextを複数のゴールーチンで使いまわしたらどうなるか
-   親のcontextをキャンセルしたら、子のcontextはどうなるか

というキャンセル伝播の詳細な仕様を探っていきたいと思います。

# [](#%E5%90%8C%E3%81%98context%E3%82%92%E4%BD%BF%E3%81%84%E3%81%BE%E3%82%8F%E3%81%97%E3%81%9F%E5%A0%B4%E5%90%88){.header-anchor-link} 同じcontextを使いまわした場合 {#%E5%90%8C%E3%81%98context%E3%82%92%E4%BD%BF%E3%81%84%E3%81%BE%E3%82%8F%E3%81%97%E3%81%9F%E5%A0%B4%E5%90%88}

## [](#%E7%9B%B4%E5%88%97%E3%81%AA%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%BC%E3%83%81%E3%83%B3%E3%81%AE%E5%A0%B4%E5%90%88){.header-anchor-link} 直列なゴールーチンの場合 {#%E7%9B%B4%E5%88%97%E3%81%AA%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%BC%E3%83%81%E3%83%B3%E3%81%AE%E5%A0%B4%E5%90%88}

例えば、以下のようなコードを考えます。

::: code-block-container
``` language-go
func main() {
    ctx0 := context.Background()

    ctx1, _ := context.WithCancel(ctx0)
    // G1
    go func(ctx1 context.Context) {
        ctx2, cancel2 := context.WithCancel(ctx1)

        // G2-1
        go func(ctx2 context.Context) {
            // G2-2
            go func(ctx2 context.Context) {
                select {
                case <-ctx2.Done():
                    fmt.Println("G2-2 canceled")
                }
            }(ctx2)

            select {
            case <-ctx2.Done():
                fmt.Println("G2-1 canceled")
            }
        }(ctx2)

        cancel2()

        select {
        case <-ctx1.Done():
            fmt.Println("G1 canceled")
        }

    }(ctx1)

    time.Sleep(time.Second)
}
```
:::

`go`文にて新規に立てられたゴールーチンはG1, G2-1, G2-2の3つ存在します。\
それらの関係と、それぞれに引数として渡されているcontextは以下のようになっています。

![](https://storage.googleapis.com/zenn-user-upload/456e1b94b95d4a84af7a9c20.png){.md-img
width="100" loading="lazy"}

`ctx2`のキャンセルのみを実行すると、G2-1とG2-2が揃って終了し、その親であるG1は生きたままとなります。

::: code-block-container
``` language-bash
$ go run main.go
G2-1 canceled
G2-2 canceled
```
:::

![](https://storage.googleapis.com/zenn-user-upload/2e888889bc778ba530fa9795.png){.md-img
width="100" loading="lazy"}

## [](#%E4%B8%A6%E5%88%97%E3%81%AA%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%BC%E3%83%81%E3%83%B3%E3%81%AE%E5%A0%B4%E5%90%88){.header-anchor-link} 並列なゴールーチンの場合 {#%E4%B8%A6%E5%88%97%E3%81%AA%E3%82%B4%E3%83%BC%E3%83%AB%E3%83%BC%E3%83%81%E3%83%B3%E3%81%AE%E5%A0%B4%E5%90%88}

::: msg
ここでの並列は、「並行処理・並列処理」の意味ではなく、直列の対義語としての並列を指します。
:::

それでは、今度は以下のコードについて考えてみましょう。

::: code-block-container
``` language-go
func main() {
    ctx0 := context.Background()

    ctx1, cancel1 := context.WithCancel(ctx0)
    // G1-1
    go func(ctx1 context.Context) {
        select {
        case <-ctx1.Done():
            fmt.Println("G1-1 canceled")
        }
    }(ctx1)

    // G1-2
    go func(ctx1 context.Context) {
        select {
        case <-ctx1.Done():
            fmt.Println("G1-2 canceled")
        }
    }(ctx1)

    cancel1()

    time.Sleep(time.Second)
}
```
:::

メイン関数の中で、`go`文を二つ並列に立てて、そこに同一のcontext`ctx1`を渡しています。

![](https://storage.googleapis.com/zenn-user-upload/88639d8b151c24b2e8082059.png){.md-img
width="300" loading="lazy"}

ここで、`ctx1`をキャンセルすると、G1-1, G1-2ともに連動して終了します。

::: code-block-container
``` language-bash
$ go run main.go
G1-1 canceled
G1-2 canceled
```
:::

![](https://storage.googleapis.com/zenn-user-upload/0346a3cc3874d8eb4f80d972.png){.md-img
width="300" loading="lazy"}

## [](#%E3%81%BE%E3%81%A8%E3%82%81){.header-anchor-link} まとめ {#%E3%81%BE%E3%81%A8%E3%82%81}

同じcontextを複数のゴールーチンに渡した場合、それらが直列の関係であろうが並列の関係であろうが同じ挙動となります。\
ゴールーチンの生死を制御するcontextが同じであるので、キャンセルタイミングも当然連動することとなります。

# [](#%E5%85%84%E5%BC%9F%E9%96%A2%E4%BF%82%E3%81%AB%E3%81%82%E3%82%8Bcontext%E3%81%AE%E5%A0%B4%E5%90%88){.header-anchor-link} 兄弟関係にあるcontextの場合 {#%E5%85%84%E5%BC%9F%E9%96%A2%E4%BF%82%E3%81%AB%E3%81%82%E3%82%8Bcontext%E3%81%AE%E5%A0%B4%E5%90%88}

続いて、以下のようなコードを考えます。

::: code-block-container
``` language-go
func main() {
    ctx0 := context.Background()

    ctx1, cancel1 := context.WithCancel(ctx0)
    // G1
    go func(ctx1 context.Context) {
        select {
        case <-ctx1.Done():
            fmt.Println("G1 canceled")
        }
    }(ctx1)

    ctx2, _ := context.WithCancel(ctx0)
    // G2
    go func(ctx2 context.Context) {
        select {
        case <-ctx2.Done():
            fmt.Println("G2 canceled")
        }
    }(ctx2)

    cancel1()

    time.Sleep(time.Second)
}
```
:::

メイン関数の中で`go`文を二つ並列に立てて、ゴールーチンG1,G2を立てています。\
そしてそれぞれには、`ctx0`を親にして作ったcontext`ctx1`,`ctx2`を渡しています。

![](https://storage.googleapis.com/zenn-user-upload/39aa7992af8d2756961aa373.png){.md-img
width="350" loading="lazy"}

ここで、`ctx1`をキャンセルすると、G1のみが終了し、G2はその影響を受けることなく生きていることが確認できます。

::: code-block-container
``` language-bash
$ go run main.go
G1 canceled
```
:::

![](https://storage.googleapis.com/zenn-user-upload/8dd67da3a1e00039c2d27c41.png){.md-img
width="350" loading="lazy"}

# [](#%E8%A6%AA%E5%AD%90%E9%96%A2%E4%BF%82%E3%81%AB%E3%81%82%E3%82%8Bcontext%E3%81%AE%E5%A0%B4%E5%90%88){.header-anchor-link} 親子関係にあるcontextの場合 {#%E8%A6%AA%E5%AD%90%E9%96%A2%E4%BF%82%E3%81%AB%E3%81%82%E3%82%8Bcontext%E3%81%AE%E5%A0%B4%E5%90%88}

以下のようなコードを考えます。

::: code-block-container
``` language-go
func main() {
    ctx0 := context.Background()

    ctx1, _ := context.WithCancel(ctx0)
    // G1
    go func(ctx1 context.Context) {
        ctx2, cancel2 := context.WithCancel(ctx1)

        // G2
        go func(ctx2 context.Context) {
            ctx3, _ := context.WithCancel(ctx2)

            // G3
            go func(ctx3 context.Context) {
                select {
                case <-ctx3.Done():
                    fmt.Println("G3 canceled")
                }
            }(ctx3)

            select {
            case <-ctx2.Done():
                fmt.Println("G2 canceled")
            }
        }(ctx2)

        cancel2()

        select {
        case <-ctx1.Done():
            fmt.Println("G1 canceled")
        }

    }(ctx1)

    time.Sleep(time.Second)
}
```
:::

`go`文にて新規に立てられたゴールーチンはG1, G2, G3の3つ存在します。\
それらの関係と、それぞれに引数として渡されているcontextは以下のようになっています。

![](https://storage.googleapis.com/zenn-user-upload/ce6205c05e055f5d9e008c79.png){.md-img
width="100" loading="lazy"}

`ctx2`のキャンセルのみを実行すると、`ctx2`ともつG2と、その子である`ctx3`を持つG3が揃って終了します。\
一方、`ctx2`の親である`ctx1`を持つG1は生きたままとなります。

::: code-block-container
``` language-bash
$ go run main.go
G2 canceled
G3 canceled
```
:::

![](https://storage.googleapis.com/zenn-user-upload/42852339abb449f4650e247f.png){.md-img
width="100" loading="lazy"}\
これで、「親contextがキャンセルされたら、子のcontextにまで波及する」ということが確認できました。

## [](#(%E3%81%8A%E3%81%BE%E3%81%91)%E5%AD%90%E3%81%8B%E3%82%89%E8%A6%AA%E3%81%AE%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB){.header-anchor-link} (おまけ)子から親のキャンセル {#(%E3%81%8A%E3%81%BE%E3%81%91)%E5%AD%90%E3%81%8B%E3%82%89%E8%A6%AA%E3%81%AE%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB}

「親から子へのキャンセル(=`ctx2`→`ctx3`)」は確認できましたが、「子から親へのキャンセル(`ctx2`→`ctx1`)」は行われませんでした。

このような設計になっていることについて、[Go公式ブログ - Go Concurrency
Patterns:
Context](https://go.dev/blog/context)では以下のように述べられています。

> **A Context does not have a Cancel method for the same reason the Done
> channel is receive-only**: the function receiving a cancelation signal
> is usually not the one that sends the signal.\
> In particular, when a parent operation starts goroutines for
> sub-operations, those sub-operations should not be able to cancel the
> parent.
>
> (訳):**contextが自発的な`Cancel`メソッドを持たないのは、doneチャネルがレシーブオンリーであるのと同じ理由です**。キャンセル信号を受信した関数が、そのままその信号を別の関数に送ることになるわけではないのです。\
> 特に、親となる関数が子関数の実行場としてゴールーチンを起動した場合、その子関数側から親関数をキャンセルするようなことはやるべきではありません。
>
> 出典:[Go公式ブログ - Go Concurrency Patterns:
> Context](https://go.dev/blog/context)
:::
:::
:::

